# Generated by Django 4.1 on 2023-04-23 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0002_member_joined_date_member_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="joined_date",
        ),
        migrations.RemoveField(
            model_name="member",
            name="phone",
        ),
    ]
