# Generated by Django 4.1 on 2023-04-25 12:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0004_customuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="last_login",
        ),
        migrations.AddField(
            model_name="customuser",
            name="mail",
            field=models.CharField(
                default="",
                max_length=128,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(6)],
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name="customuser",
            table=None,
        ),
    ]
