# Generated by Django 4.1 on 2023-04-28 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0009_remove_member_user_member_email_member_password"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FullName",
            new_name="Approved",
        ),
    ]
