# Generated by Django 4.1 on 2023-04-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0010_rename_fullname_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="approved",
            name="image",
            field=models.ImageField(default=5, upload_to="approved_images/"),
            preserve_default=False,
        ),
    ]
